### ISSUE TITLE
로고

### ISSUE THREAD

**Issue by mixed** [NAVER-FEPlatform/FEDevtalk#2]
![리디](https://user-images.githubusercontent.com/22300/115655479-5bfd7780-a36e-11eb-9ff8-1627c00b1643.png)
![마이리얼트립](https://user-images.githubusercontent.com/22300/115655482-5d2ea480-a36e-11eb-8e3e-f8f69e101a80.png)
![마플](https://user-images.githubusercontent.com/22300/115655483-5dc73b00-a36e-11eb-98e2-d6d10bc44da8.jpeg)
![빙글](https://user-images.githubusercontent.com/22300/115655486-5ef86800-a36e-11eb-9ee5-24f49ef87dd3.jpeg)
![쏘카](https://user-images.githubusercontent.com/22300/115655489-5ef86800-a36e-11eb-9347-ba173f51c1ed.png)
![와인포인트](https://user-images.githubusercontent.com/22300/115655490-5f90fe80-a36e-11eb-9b50-00d9b15abe23.png)
![중앙일보](https://user-images.githubusercontent.com/22300/115655492-60299500-a36e-11eb-8fa8-febe889aeef7.png)

![하이퍼커넥트](https://user-images.githubusercontent.com/22300/115655498-60c22b80-a36e-11eb-96b5-fe625ec82a48.png)
![lablup](https://user-images.githubusercontent.com/22300/115655499-60c22b80-a36e-11eb-8f53-d0041b5726df.png)

<img width="408" alt="루닛" src="https://user-images.githubusercontent.com/22300/115655659-b4347980-a36e-11eb-843d-69dcfc4626d8.png">

<img width="410" alt="진인사" src="https://user-images.githubusercontent.com/22300/115655755-e645db80-a36e-11eb-929c-20aee598d922.png">

![프로토파이](https://user-images.githubusercontent.com/22300/115655663-b5fe3d00-a36e-11eb-9d7c-1d04d2508450.png)

**Comment by BillionaireDY** [comment]
![bank-salad](https://user-images.githubusercontent.com/14918660/119443507-b1111c80-bd64-11eb-953c-c96c96bdd038.png)
![kakao](https://user-images.githubusercontent.com/14918660/119443512-b2dae000-bd64-11eb-818a-9623b392906c.png)
![dano-primary-logo](https://user-images.githubusercontent.com/14918660/119443515-b3737680-bd64-11eb-852d-d03ae448d9b2.png)
